version: '3.7'
services:
  dolmagic-nginx:
    image: dolmagic-nginx:${IMAGE_TAG}
    container_name: dolmagic-app-nginx
    ports:
      - ${TEST_WEB_PORT}:80
    volumes:
      - .:/app
    depends_on:
      - dolmagic-php-fpm
      - dolmagic-redis

  dolmagic-redis:
    image: redis:3.2.10-alpine
    container_name: dolmagic-app-redis
    ports:
      - 63791:6379

  dolmagic-mariadb:
    image: mariadb:10.1.32
    container_name: dolmagic-app-mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${TEST_DB_PATH}:/var/lib/mysql
      - ./docker/development/mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 33061:3306

  dolmagic-php-fpm:
    image: dolmagic-php-fpm:${IMAGE_TAG}
    container_name: dolmagic-app-php-fpm
    volumes:
      - .:/app

  dolmagic-php-cli:
    image: dolmagic-php-cli:${IMAGE_TAG}
    container_name: dolmagic-app-php-cli
    volumes:
      - .:/app

  dolmagic-node-cli:
    image: node:12.18.2-alpine
    container_name: dolmagic-app-node-cli
    volumes:
      - .:/app
    working_dir: /app

networks:
  default:
    name: dolmagic-dev_default